COMPOSITION_NAME = "baseline"
BUILD_SELECTORS = [ "hardened_api",]
GS_VERSION = "4f56e8f0a75b06aff68ae79717915ebadc1698f6"
T_RUN = "5m"
T_WARM = "5s"
N_NODES = 20
N_ATTACK_NODES = 0
ATTACK_NODE_TYPE = "sybil"
N_PUBLISHER = 10
T_SCORE_INSPECT_PERIOD = "5s"
N_CONTAINER_NODES_TOTAL = 20
[[TOPIC_CONFIG]]
id = "blocks"
message_rate = "120/s"
message_size = "2 KiB"

[PEER_SCORE_PARAMS]
IPColocationFactorWeight = 0
IPColocationFactorThreshold = 1
DecayInterval = "5s"
DecayToZero = 0.01
RetainScore = "10s"

[PEER_SCORE_PARAMS.Thresholds]
GossipThreshold = -4000
PublishThreshold = -5000
GraylistThreshold = -10000
AcceptPXThreshold = 0

[PEER_SCORE_PARAMS.Topics.blocks]
TopicWeight = 0.25
TimeInMeshWeight = 0.0027
TimeInMeshQuantum = "1s"
TimeInMeshCap = 3600
FirstMessageDeliveriesWeight = 0.664
FirstMessageDeliveriesDecay = 0.9916
FirstMessageDeliveriesCap = 1500
MeshMessageDeliveriesWeight = -0.25
MeshMessageDeliveriesDecay = 0.97
MeshMessageDeliveriesCap = 400
MeshMessageDeliveriesThreshold = 100
MeshMessageDeliveriesActivation = "30s"
MeshMessageDeliveryWindow = "5ms"
MeshFailurePenaltyWeight = -0.25
MeshFailurePenaltyDecay = 0.997
InvalidMessageDeliveriesWeight = -99
InvalidMessageDeliveriesDecay = 0.9994
