apiVersion: v1
kind: Service
metadata:
  labels:
    app: lighthouse-beacon
  name: lighthouse-beacon
spec:
  ports:
  - name: http
    port: 5052
    targetPort: 5052
    protocol: TCP
  - name: monitoring
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: ligh-tcp
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: light-udp
    port: 9000
    targetPort: 9000
    protocol: UDP
  selector:
    app: lighthouse-beacon
